# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/add_remove_clan.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddRemoveClan(object):
    def setupUi(self, AddRemoveClan):
        AddRemoveClan.setObjectName("AddRemoveClan")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("ui/Icons/Select.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        AddRemoveClan.setWindowIcon(icon)
        AddRemoveClan.setStyleSheet("background-color: rgb(32, 33, 37);")
        AddRemoveClan.setModal(True)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(AddRemoveClan)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.main_frame = QtWidgets.QFrame(AddRemoveClan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.main_frame.sizePolicy().hasHeightForWidth())
        self.main_frame.setSizePolicy(sizePolicy)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.main_frame)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_top = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_left.sizePolicy().hasHeightForWidth())
        self.frame_left.setSizePolicy(sizePolicy)
        self.frame_left.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_left.setObjectName("frame_left")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_left)
        self.verticalLayout.setContentsMargins(0, 0, 6, 0)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_addClan = QtWidgets.QLabel(self.frame_left)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_addClan.setFont(font)
        self.label_addClan.setMouseTracking(True)
        self.label_addClan.setStyleSheet("color: white;")
        self.label_addClan.setTextFormat(QtCore.Qt.AutoText)
        self.label_addClan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_addClan.setObjectName("label_addClan")
        self.verticalLayout.addWidget(self.label_addClan)
        self.lineEdit_addClan = QtWidgets.QLineEdit(self.frame_left)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.lineEdit_addClan.setFont(font)
        self.lineEdit_addClan.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.lineEdit_addClan.setText("")
        self.lineEdit_addClan.setCursorMoveStyle(QtCore.Qt.LogicalMoveStyle)
        self.lineEdit_addClan.setClearButtonEnabled(True)
        self.lineEdit_addClan.setObjectName("lineEdit_addClan")
        self.verticalLayout.addWidget(self.lineEdit_addClan)
        self.label_or = QtWidgets.QLabel(self.frame_left)
        self.label_or.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_or.setFont(font)
        self.label_or.setStyleSheet("color: white;")
        self.label_or.setTextFormat(QtCore.Qt.AutoText)
        self.label_or.setAlignment(QtCore.Qt.AlignCenter)
        self.label_or.setObjectName("label_or")
        self.verticalLayout.addWidget(self.label_or, 0, QtCore.Qt.AlignRight|QtCore.Qt.AlignBottom)
        self.label_removeClan = QtWidgets.QLabel(self.frame_left)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_removeClan.setFont(font)
        self.label_removeClan.setStyleSheet("color: white;")
        self.label_removeClan.setTextFormat(QtCore.Qt.AutoText)
        self.label_removeClan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_removeClan.setObjectName("label_removeClan")
        self.verticalLayout.addWidget(self.label_removeClan)
        self.comboBox_RemoveClan = QtWidgets.QComboBox(self.frame_left)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(14)
        self.comboBox_RemoveClan.setFont(font)
        self.comboBox_RemoveClan.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);")
        self.comboBox_RemoveClan.setObjectName("comboBox_RemoveClan")
        self.comboBox_RemoveClan.addItem("")
        self.comboBox_RemoveClan.setItemText(0, "")
        self.verticalLayout.addWidget(self.comboBox_RemoveClan)
        self.horizontalLayout_2.addWidget(self.frame_left)
        self.line = QtWidgets.QFrame(self.frame_top)
        self.line.setMinimumSize(QtCore.QSize(0, 160))
        self.line.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.frame_right = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_right.sizePolicy().hasHeightForWidth())
        self.frame_right.setSizePolicy(sizePolicy)
        self.frame_right.setObjectName("frame_right")
        self.gridLayout = QtWidgets.QGridLayout(self.frame_right)
        self.gridLayout.setContentsMargins(6, -1, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.label_note = QtWidgets.QLabel(self.frame_right)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_note.sizePolicy().hasHeightForWidth())
        self.label_note.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(10)
        self.label_note.setFont(font)
        self.label_note.setStyleSheet("color: white;")
        self.label_note.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_note.setWordWrap(True)
        self.label_note.setObjectName("label_note")
        self.gridLayout.addWidget(self.label_note, 0, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame_right)
        self.gridLayout_2.addWidget(self.frame_top, 1, 0, 1, 1)
        self.frame_button = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_button.sizePolicy().hasHeightForWidth())
        self.frame_button.setSizePolicy(sizePolicy)
        self.frame_button.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_button.setObjectName("frame_button")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.frame_button)
        self.gridLayout_4.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.pushButton_done = QtWidgets.QPushButton(self.frame_button)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00c580;\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(38, 127, 51, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 136, 86);\n"
"}")
        self.pushButton_done.setObjectName("pushButton_done")
        self.gridLayout_4.addWidget(self.pushButton_done, 1, 0, 1, 1)
        self.line_3 = QtWidgets.QFrame(self.frame_button)
        self.line_3.setMinimumSize(QtCore.QSize(270, 4))
        self.line_3.setMaximumSize(QtCore.QSize(270, 4))
        self.line_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.line_3.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.gridLayout_4.addWidget(self.line_3, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame_button, 2, 0, 1, 1)
        self.verticalLayout_2.addWidget(self.main_frame)

        self.retranslateUi(AddRemoveClan)
        QtCore.QMetaObject.connectSlotsByName(AddRemoveClan)

    def retranslateUi(self, AddRemoveClan):
        _translate = QtCore.QCoreApplication.translate
        AddRemoveClan.setWindowTitle(_translate("AddRemoveClan", "Родини"))
        self.label_addClan.setText(_translate("AddRemoveClan", "<html><head/><body><p>Додати рід <span style=\" color:#fb4938;\">*</span></p></body></html>"))
        self.label_or.setText(_translate("AddRemoveClan", "або"))
        self.label_removeClan.setText(_translate("AddRemoveClan", " Видалити рід"))
        self.label_note.setText(_translate("AddRemoveClan", "<html><head/><body><p><span style=\" color:#fb4938;\">* </span>Прізвище роду записується в родовому відмінку множини. Наприклад: Мельник - <span style=\" font-weight:600;\">Мельників</span></p></body></html>"))
        self.pushButton_done.setText(_translate("AddRemoveClan", "Готово"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddRemoveClan = QtWidgets.QDialog()
    ui = Ui_AddRemoveClan()
    ui.setupUi(AddRemoveClan)
    AddRemoveClan.show()
    sys.exit(app.exec_())
