# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ui/family_ties.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FamilyTies(object):
    def setupUi(self, FamilyTies):
        FamilyTies.setObjectName("FamilyTies")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/icons/Family.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        FamilyTies.setWindowIcon(icon)
        FamilyTies.setStyleSheet("background-color: rgb(32, 33, 37);")
        self.verticalLayout = QtWidgets.QVBoxLayout(FamilyTies)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(FamilyTies)
        self.main_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.main_frame.setObjectName("main_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.main_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 10)
        self.verticalLayout_2.setSpacing(5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.frame_choiceClan = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_choiceClan.sizePolicy().hasHeightForWidth())
        self.frame_choiceClan.setSizePolicy(sizePolicy)
        self.frame_choiceClan.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_choiceClan.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_choiceClan.setObjectName("frame_choiceClan")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_choiceClan)
        self.horizontalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_clan = QtWidgets.QLabel(self.frame_choiceClan)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(15)
        font.setBold(True)
        font.setWeight(75)
        self.label_clan.setFont(font)
        self.label_clan.setStyleSheet("color: white;")
        self.label_clan.setTextFormat(QtCore.Qt.AutoText)
        self.label_clan.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_clan.setObjectName("label_clan")
        self.horizontalLayout_3.addWidget(self.label_clan, 0, QtCore.Qt.AlignVCenter)
        self.comboBox_clan = QtWidgets.QComboBox(self.frame_choiceClan)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_clan.sizePolicy().hasHeightForWidth())
        self.comboBox_clan.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_clan.setFont(font)
        self.comboBox_clan.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_clan.setObjectName("comboBox_clan")
        self.horizontalLayout_3.addWidget(self.comboBox_clan)
        self.verticalLayout_2.addWidget(self.frame_choiceClan, 0, QtCore.Qt.AlignVCenter)
        self.line_horCenter_2 = QtWidgets.QFrame(self.main_frame)
        self.line_horCenter_2.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_horCenter_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horCenter_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horCenter_2.setObjectName("line_horCenter_2")
        self.verticalLayout_2.addWidget(self.line_horCenter_2)
        self.frame_top = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_top.sizePolicy().hasHeightForWidth())
        self.frame_top.setSizePolicy(sizePolicy)
        self.frame_top.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.frame_top)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.left_frame_1 = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame_1.sizePolicy().hasHeightForWidth())
        self.left_frame_1.setSizePolicy(sizePolicy)
        self.left_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame_1.setObjectName("left_frame_1")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.left_frame_1)
        self.verticalLayout_3.setContentsMargins(0, 10, 6, 0)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_father = QtWidgets.QLabel(self.left_frame_1)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_father.setFont(font)
        self.label_father.setStyleSheet("color: white;")
        self.label_father.setTextFormat(QtCore.Qt.AutoText)
        self.label_father.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_father.setObjectName("label_father")
        self.verticalLayout_3.addWidget(self.label_father)
        self.comboBox_father = QtWidgets.QComboBox(self.left_frame_1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_father.sizePolicy().hasHeightForWidth())
        self.comboBox_father.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_father.setFont(font)
        self.comboBox_father.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_father.setObjectName("comboBox_father")
        self.verticalLayout_3.addWidget(self.comboBox_father)
        self.horizontalLayout.addWidget(self.left_frame_1)
        self.right_frame_1 = QtWidgets.QFrame(self.frame_top)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame_1.sizePolicy().hasHeightForWidth())
        self.right_frame_1.setSizePolicy(sizePolicy)
        self.right_frame_1.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame_1.setObjectName("right_frame_1")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.right_frame_1)
        self.verticalLayout_4.setContentsMargins(6, 10, 0, 0)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_mother = QtWidgets.QLabel(self.right_frame_1)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_mother.setFont(font)
        self.label_mother.setStyleSheet("color: white;")
        self.label_mother.setTextFormat(QtCore.Qt.AutoText)
        self.label_mother.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_mother.setObjectName("label_mother")
        self.verticalLayout_4.addWidget(self.label_mother)
        self.comboBox_mother = QtWidgets.QComboBox(self.right_frame_1)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_mother.setFont(font)
        self.comboBox_mother.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_mother.setObjectName("comboBox_mother")
        self.verticalLayout_4.addWidget(self.comboBox_mother)
        self.horizontalLayout.addWidget(self.right_frame_1)
        self.verticalLayout_2.addWidget(self.frame_top)
        self.line_horTop = QtWidgets.QFrame(self.main_frame)
        self.line_horTop.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_horTop.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horTop.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horTop.setObjectName("line_horTop")
        self.verticalLayout_2.addWidget(self.line_horTop)
        self.frame_center = QtWidgets.QFrame(self.main_frame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_center.sizePolicy().hasHeightForWidth())
        self.frame_center.setSizePolicy(sizePolicy)
        self.frame_center.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_center.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_center.setObjectName("frame_center")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame_center)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.left_frame_2 = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.left_frame_2.sizePolicy().hasHeightForWidth())
        self.left_frame_2.setSizePolicy(sizePolicy)
        self.left_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.left_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.left_frame_2.setObjectName("left_frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.left_frame_2)
        self.verticalLayout_6.setContentsMargins(0, 10, 6, 0)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_BS = QtWidgets.QLabel(self.left_frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(12)
        self.label_BS.setFont(font)
        self.label_BS.setStyleSheet("color: white;")
        self.label_BS.setTextFormat(QtCore.Qt.AutoText)
        self.label_BS.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_BS.setObjectName("label_BS")
        self.verticalLayout_6.addWidget(self.label_BS)
        self.comboBox_siblings = QtWidgets.QComboBox(self.left_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_siblings.sizePolicy().hasHeightForWidth())
        self.comboBox_siblings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_siblings.setFont(font)
        self.comboBox_siblings.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_siblings.setObjectName("comboBox_siblings")
        self.verticalLayout_6.addWidget(self.comboBox_siblings)
        self.pushButton_addSiblings = QtWidgets.QPushButton(self.left_frame_2)
        self.pushButton_addSiblings.setMinimumSize(QtCore.QSize(30, 45))
        self.pushButton_addSiblings.setMaximumSize(QtCore.QSize(30, 45))
        self.pushButton_addSiblings.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_addSiblings.setStyleSheet("QPushButton {\n"
"    background-position: center center;\n"
"    background-repeat: no-repeat;\n"
"    background-attachment: fixed;\n"
"    border: none;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-image: url(:/icons/Add_color_pressed.ico);\n"
"    background-position: center center;\n"
"    background-repeat: no-repeat;\n"
"    background-attachment: fixed;\n"
"    border: none;\n"
"}")
        self.pushButton_addSiblings.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/icons/Add_color.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.pushButton_addSiblings.setIcon(icon1)
        self.pushButton_addSiblings.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_addSiblings.setObjectName("pushButton_addSiblings")
        self.verticalLayout_6.addWidget(self.pushButton_addSiblings, 0, QtCore.Qt.AlignHCenter)
        self.tableWidget_siblings = QtWidgets.QTableWidget(self.left_frame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget_siblings.sizePolicy().hasHeightForWidth())
        self.tableWidget_siblings.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(12)
        self.tableWidget_siblings.setFont(font)
        self.tableWidget_siblings.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 5px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.tableWidget_siblings.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tableWidget_siblings.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.tableWidget_siblings.setRowCount(0)
        self.tableWidget_siblings.setColumnCount(1)
        self.tableWidget_siblings.setObjectName("tableWidget_siblings")
        self.tableWidget_siblings.horizontalHeader().setVisible(False)
        self.tableWidget_siblings.horizontalHeader().setDefaultSectionSize(375)
        self.verticalLayout_6.addWidget(self.tableWidget_siblings)
        self.horizontalLayout_2.addWidget(self.left_frame_2, 0, QtCore.Qt.AlignTop)
        self.line_vertCenter = QtWidgets.QFrame(self.frame_center)
        self.line_vertCenter.setMinimumSize(QtCore.QSize(20, 0))
        self.line_vertCenter.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_vertCenter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_vertCenter.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_vertCenter.setObjectName("line_vertCenter")
        self.horizontalLayout_2.addWidget(self.line_vertCenter)
        self.right_frame_2 = QtWidgets.QFrame(self.frame_center)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.right_frame_2.sizePolicy().hasHeightForWidth())
        self.right_frame_2.setSizePolicy(sizePolicy)
        self.right_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.right_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.right_frame_2.setObjectName("right_frame_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.right_frame_2)
        self.verticalLayout_5.setContentsMargins(6, 10, 0, 0)
        self.verticalLayout_5.setSpacing(6)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_petson = QtWidgets.QLabel(self.right_frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_petson.setFont(font)
        self.label_petson.setStyleSheet("color: white;")
        self.label_petson.setTextFormat(QtCore.Qt.AutoText)
        self.label_petson.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_petson.setObjectName("label_petson")
        self.verticalLayout_5.addWidget(self.label_petson)
        self.comboBox_person = QtWidgets.QComboBox(self.right_frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_person.setFont(font)
        self.comboBox_person.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_person.setObjectName("comboBox_person")
        self.comboBox_person.addItem("")
        self.comboBox_person.setItemText(0, "")
        self.verticalLayout_5.addWidget(self.comboBox_person)
        self.pushButton_disable = QtWidgets.QPushButton(self.right_frame_2)
        self.pushButton_disable.setEnabled(False)
        self.pushButton_disable.setMinimumSize(QtCore.QSize(30, 45))
        self.pushButton_disable.setStyleSheet("QPushButton {\n"
"    background-image: url(:/icons/Add.ico);\n"
"    background-position: center center;\n"
"    background-repeat: no-repeat;\n"
"    background-attachment: fixed;\n"
"    border: none;\n"
"}")
        self.pushButton_disable.setText("")
        self.pushButton_disable.setIcon(icon1)
        self.pushButton_disable.setIconSize(QtCore.QSize(40, 40))
        self.pushButton_disable.setObjectName("pushButton_disable")
        self.verticalLayout_5.addWidget(self.pushButton_disable, 0, QtCore.Qt.AlignHCenter)
        self.label_partner = QtWidgets.QLabel(self.right_frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label_partner.setFont(font)
        self.label_partner.setStyleSheet("color: white;")
        self.label_partner.setTextFormat(QtCore.Qt.AutoText)
        self.label_partner.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_partner.setObjectName("label_partner")
        self.verticalLayout_5.addWidget(self.label_partner)
        self.comboBox_partner = QtWidgets.QComboBox(self.right_frame_2)
        font = QtGui.QFont()
        font.setFamily("Monotype Corsiva")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.comboBox_partner.setFont(font)
        self.comboBox_partner.setStyleSheet("background-color: rgba(21, 22, 26, 255);\n"
"color: rgb(190, 190, 190);\n"
"border-radius: 10px;\n"
"border-bottom: 2px solid rgb(80, 80, 85);\n"
"border-right: 2px solid rgb(80, 80, 85);\n"
"border-top: 2px solid rgb(80, 80, 85);\n"
"border-left: 2px solid rgb(80, 80, 85);\n"
"selection-background-color: white;\n"
"selection-color:rgba(21, 22, 26, 255);\n"
"")
        self.comboBox_partner.setObjectName("comboBox_partner")
        self.verticalLayout_5.addWidget(self.comboBox_partner)
        self.horizontalLayout_2.addWidget(self.right_frame_2)
        self.verticalLayout_2.addWidget(self.frame_center, 0, QtCore.Qt.AlignVCenter)
        self.line_horCenter = QtWidgets.QFrame(self.main_frame)
        self.line_horCenter.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_horCenter.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horCenter.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horCenter.setObjectName("line_horCenter")
        self.verticalLayout_2.addWidget(self.line_horCenter)
        self.line_horBottom = QtWidgets.QFrame(self.main_frame)
        self.line_horBottom.setMinimumSize(QtCore.QSize(270, 4))
        self.line_horBottom.setMaximumSize(QtCore.QSize(270, 4))
        self.line_horBottom.setStyleSheet("Line{\n"
"    color: rgb(21, 22, 26);\n"
"}")
        self.line_horBottom.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_horBottom.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_horBottom.setObjectName("line_horBottom")
        self.verticalLayout_2.addWidget(self.line_horBottom, 0, QtCore.Qt.AlignHCenter)
        self.pushButton_done = QtWidgets.QPushButton(self.main_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe Print")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_done.setFont(font)
        self.pushButton_done.setStyleSheet("QPushButton {\n"
"    text-align: center;\n"
"    background-color: rgb(80, 80, 85);\n"
"    border-bottom: 2px solid rgba(70, 70, 70, 150);\n"
"    border-radius: 8px;\n"
"    padding: 5px;\n"
"    color: rgb(32, 33, 37);\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #00c580;\n"
"    color: white;\n"
"    border: none;\n"
"    float: right;\n"
"    padding: 5px;\n"
"    border-bottom: 2px solid rgba(38, 127, 51, 130);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(0, 136, 86);\n"
"}")
        self.pushButton_done.setObjectName("pushButton_done")
        self.verticalLayout_2.addWidget(self.pushButton_done, 0, QtCore.Qt.AlignHCenter)
        self.verticalLayout.addWidget(self.main_frame)

        self.retranslateUi(FamilyTies)
        QtCore.QMetaObject.connectSlotsByName(FamilyTies)

    def retranslateUi(self, FamilyTies):
        _translate = QtCore.QCoreApplication.translate
        FamilyTies.setWindowTitle(_translate("FamilyTies", "Сімейні зв\'язки"))
        self.label_clan.setText(_translate("FamilyTies", "Рід: "))
        self.label_father.setText(_translate("FamilyTies", "Батько:"))
        self.label_mother.setText(_translate("FamilyTies", "Мати:"))
        self.label_BS.setText(_translate("FamilyTies", "Брати/Сестри:"))
        self.label_petson.setText(_translate("FamilyTies", "<html><head/><body><p>Встановити сімейні зв\'язки для <span style=\" color:#fb4938;\">*</span>:</p></body></html>"))
        self.label_partner.setText(_translate("FamilyTies", "Партнер:"))
        self.pushButton_done.setText(_translate("FamilyTies", "Готово"))
import media_resources_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FamilyTies = QtWidgets.QDialog()
    ui = Ui_FamilyTies()
    ui.setupUi(FamilyTies)
    FamilyTies.show()
    sys.exit(app.exec_())
